#!/bin/bash

TMP_FILE=/tmp/applauncher

open() {
    ~/.config/rofi/rofiscript.sh
    polybar-msg -p $(cat /tmp/tablet_launcher_pid) cmd show
    echo open > $TMP_FILE
    polybar-msg -p $(cat /tmp/tablet_pid) hook applauncher 1
}

close() {
    polybar-msg -p $(cat /tmp/tablet_launcher_pid) cmd hide
    echo closed > $TMP_FILE
    polybar-msg -p $(cat /tmp/tablet_pid) hook applauncher 1
}

is_open() {
    if [ "$(cat $TMP_FILE)" == "open" ]; then
        return 0
    else
        return 1
    fi
}

toggle() {
    if is_open; then
        close
    else
        open
    fi
}

launch() {
    ID=$(cat $TMP_FILE)
    case "$1" in
        stacked)
            ~/.config/rofi/rofiscript.sh &
            ;;
        *)
            exit
    esac
    kill $ID
    close
}

icon() {
    COLOR_BASE="%{F#FFFF00}"
    COLOR_ACTIVE="%{F#268BD2}"
    COLOR_END="%{F-}"


    if is_open; then
        echo "$COLOR_ACTIVE     $COLOR_END"
    else
        echo "$COLOR_BASE     $COLOR_END"
    fi
}

case "$1" in
    launch)
        launch $2;;
    open)
        open;;
    close)
        close;;
    toggle)
        toggle;;
    icon)
        icon;;
    is_open)
        is_open;;
    *)
        echo "Unknown option $1"
        echo "applauncher [launch|open|close|toggle|is_open]"
esac




